### ISSUE TITLE
Many updates to follow standards

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-camel#3]
I am probably going to miss things, but here's a pass at it..

For root pom.xml:
- inherit from sonatype parent
- include licence 
- include scm
- include distributionManagement
- add sonar.\* properties
- add release profile
- add coveralls and cobertura plugins to build

Thought there might be other things, but I don't notice anything missing outside of the pom.

**Comment by jewzaam** [comment]
Oh, here on github create labels with correct colors to be consistent with other repos (see lightblue-core as the canonical standard).

**Comment by dcrissman** [comment]
label colors changed
